language: python

python:
  - "2.7"

branches:
  only:
    - master

before_script:
  - pwd
  - python --version
  - python2 --version
  - mysql -e 'create database IF NOT EXISTS pygamescores;'

# Command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pygame
  - "pip install -r dependencies.txt"

# Command to run tests
script:
  - python Snake.py
  - python test_DBConnect.py