language: python

python:
  - "2.7"

#virtualenv:
#  system_site_packages: true

branches:
  only:
    - master

before_script:
  - echo "Entered before_script..."
  - echo "directory -> "; pwd
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('jfkd') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  #- mysql grant all privilges on *.* to 'root'@'localhost' with grant option
  - mysql -e 'create database IF NOT EXISTS pygamescores;'

# Command to install dependencies
install:
  - echo "Entered install..."
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pygame
  - "pip install -r dependencies.txt"

# Command to run tests
script:
  - echo "Entered script..."
  - python Snake.py
  - python test_DBConnect.py