language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master

before_script:
  - echo "Entered before_script..."

  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('jfkd') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS pygamescores;'

# Command to install dependencies
install:
  - echo "Entered install..."

  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame

  - pip install -r dependencies.txt
  - pip install python-coveralls
  #- pip install scrutinizer-ocular
  #- ocular --data-file ".coverage" --config-file ".coveragerc"

# Command to run tests
script:
  - echo "Entered script..."
  - python Snake.py -t
  #- python test_DBConnect.py
  - coverage run test_DBConnect.py

after_sucess:
  - coveralls