language: python

python:
  - "2.7"

branches:
  only:
    - master

before_script:
  - mysql -e 'create database <<pygamescores>>;'

# Command to install dependencies
install:
  - "pip install -r dependencies.txt"

# Command to run tests
script:
  - python snake_game/test_DBConnect.py